export const API_ENDPOINTS = {
  auth: {
    login: "/auth/login",
    register: "/auth/register",
    refresh: "/auth/refresh",
    logout: "/auth/logout",
    me: "/auth/me",
  },
  orders: {
    mine: "/orders/my",
    available: "/orders/available",
    create: "/orders",
    detail: (id: string) => `/orders/${id}`,
    update: (id: string) => `/orders/${id}`,
    updateStatus: (id: string) => `/orders/${id}/status`,
    assign: (id: string) => `/orders/${id}/assign`,
    delete: (id: string) => `/orders/${id}`,
  },
  carrier: {
    apply: "/carrier/apply",
    profile: "/carrier/profile",
  },
  vehicles: {
    list: "/vehicles",
    create: "/vehicles",
    update: (id: string) => `/vehicles/${id}`,
    delete: (id: string) => `/vehicles/${id}`,
  },
  routes: {
    calculate: "/routes/calculate",
    plan: "/routes/plan",
  },
  settlements: {
    list: "/settlements",
    detail: (id: string) => `/settlements/${id}`,
  },
  analytics: {
    flows: "/analytics/flows",
    regionalSummary: "/analytics/regional-summary",
    economic: "/analytics/economic",
  },
  routeConditions: {
    forOrder: (id: string) => `/route-conditions/${id}`,
  },
  devices: {
    list: "/devices",
    create: "/devices",
    attachVehicle: (id: string) => `/devices/${id}/vehicle`,
    rotateSecret: (id: string) => `/devices/${id}/rotate-secret`,
    delete: (id: string) => `/devices/${id}`,
  },
  telemetry: {
    deviceLast: (id: string) => `/telemetry/devices/${id}/last`,
    deviceHistory: (id: string) => `/telemetry/devices/${id}/history`,
    vehicleLast: (id: string) => `/telemetry/vehicles/${id}/last`,
    vehicleHistory: (id: string) => `/telemetry/vehicles/${id}/history`,
    orderLive: (id: string) => `/telemetry/orders/${id}/live`,
    orderHistory: (id: string) => `/telemetry/orders/${id}/history`,
  },
  alerts: {
    rules: "/alerts/rules",
    updateRule: (id: string) => `/alerts/rules/${id}`,
    deleteRule: (id: string) => `/alerts/rules/${id}`,
    list: "/alerts",
    acknowledge: (id: string) => `/alerts/${id}/acknowledge`,
    resolve: (id: string) => `/alerts/${id}/resolve`,
  },
  predictions: {
    land: "/predictions/land",
  },
  cameras: {
    orderLatest: (id: string) => `/cameras/orders/${id}/latest`,
    deviceLatest: (id: string) => `/cameras/devices/${id}/latest`,
  },
  superadmin: {
    users: "/superadmin/users",
    user: (id: string) => `/superadmin/users/${id}`,
    userRole: (id: string) => `/superadmin/users/${id}/role`,
    userStatus: (id: string) => `/superadmin/users/${id}/status`,
    userPassword: (id: string) => `/superadmin/users/${id}/password`,
    carriers: "/superadmin/carriers",
    carrierApproval: (id: string) => `/superadmin/carriers/${id}/approval`,
    vehicles: "/superadmin/vehicles",
    orders: "/superadmin/orders",
    order: (id: string) => `/superadmin/orders/${id}`,
  },
  uploads: {
    avatar: "/uploads/avatar",
    cargo: "/uploads/cargo",
    product: "/uploads/product",
  },
} as const;
