/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as MapRouteImport } from './routes/map'
import { Route as HotspotsRouteImport } from './routes/hotspots'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as PoliceRouteImport } from './routes/police'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PredictionsRouteImport } from './routes/predictions'
import { Route as RoadsIndexRouteImport } from './routes/roads.index'
import { Route as RoadsRoadIdRouteImport } from './routes/roads.$roadId'
import { Route as PredictionsPredictionIdRouteImport } from './routes/predictions.$predictionId'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as AdminModelRegistryRouteImport } from './routes/admin.model-registry'
import { Route as AdminHistoryRouteImport } from './routes/admin.history'
import { Route as AnalyticsPredictionIdRouteImport } from './routes/analytics.$predictionId'
import { Route as AdminDataManagementRouteImport } from './routes/admin.data-management'

const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const HotspotsRoute = HotspotsRouteImport.update({
  id: '/hotspots',
  path: '/hotspots',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsPredictionIdRoute = AnalyticsPredictionIdRouteImport.update({
  id: '/graph-analytics/$predictionId',
  path: '/graph-analytics/$predictionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliceRoute = PoliceRouteImport.update({
  id: '/police',
  path: '/police',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadsIndexRoute = RoadsIndexRouteImport.update({
  id: '/roads/',
  path: '/roads/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadsRoadIdRoute = RoadsRoadIdRouteImport.update({
  id: '/roads/$roadId',
  path: '/roads/$roadId',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsRoute = PredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsPredictionIdRoute = PredictionsPredictionIdRouteImport.update({
  id: '/predictions/$predictionId',
  path: '/predictions/$predictionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModelRegistryRoute = AdminModelRegistryRouteImport.update({
  id: '/model-registry',
  path: '/model-registry',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHistoryRoute = AdminHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDataManagementRoute = AdminDataManagementRouteImport.update({
  id: '/data-management',
  path: '/data-management',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/graph-analytics/$predictionId': typeof AnalyticsPredictionIdRoute
  '/police': typeof PoliceRoute
  '/predictions': typeof PredictionsRoute
  '/hotspots': typeof HotspotsRoute
  '/map': typeof MapRoute
  '/reports': typeof ReportsRoute
  '/submit': typeof SubmitRoute
  '/admin/data-management': typeof AdminDataManagementRoute
  '/admin/history': typeof AdminHistoryRoute
  '/admin/model-registry': typeof AdminModelRegistryRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/predictions/$predictionId': typeof PredictionsPredictionIdRoute
  '/roads/$roadId': typeof RoadsRoadIdRoute
  '/roads/': typeof RoadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/graph-analytics/$predictionId': typeof AnalyticsPredictionIdRoute
  '/police': typeof PoliceRoute
  '/predictions': typeof PredictionsRoute
  '/hotspots': typeof HotspotsRoute
  '/map': typeof MapRoute
  '/reports': typeof ReportsRoute
  '/submit': typeof SubmitRoute
  '/admin/data-management': typeof AdminDataManagementRoute
  '/admin/history': typeof AdminHistoryRoute
  '/admin/model-registry': typeof AdminModelRegistryRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/predictions/$predictionId': typeof PredictionsPredictionIdRoute
  '/roads/$roadId': typeof RoadsRoadIdRoute
  '/roads': typeof RoadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/graph-analytics/$predictionId': typeof AnalyticsPredictionIdRoute
  '/police': typeof PoliceRoute,
  '/predictions': typeof PredictionsRoute,
  '/hotspots': typeof HotspotsRoute,
  '/map': typeof MapRoute
  '/reports': typeof ReportsRoute
  '/submit': typeof SubmitRoute
  '/admin/data-management': typeof AdminDataManagementRoute
  '/admin/history': typeof AdminHistoryRoute
  '/admin/model-registry': typeof AdminModelRegistryRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/predictions/$predictionId': typeof PredictionsPredictionIdRoute
  '/roads/$roadId': typeof RoadsRoadIdRoute
  '/roads/': typeof RoadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/graph-analytics/$predictionId'
    | '/hotspots'
    | '/map'
    | '/police'
    | '/predictions'
    | '/reports'
    | '/submit'
    | '/admin/data-management'
    | '/admin/history'
    | '/admin/model-registry'
    | '/admin/moderation'
    | '/predictions/$predictionId'
    | '/roads/$roadId'
    | '/roads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analytics'
    | '/graph-analytics/$predictionId'
    | '/hotspots'
    | '/map'
    | '/police'
    | '/predictions'
    | '/reports'
    | '/submit'
    | '/admin/data-management'
    | '/admin/history'
    | '/admin/model-registry'
    | '/admin/moderation'
    | '/predictions/$predictionId'
    | '/roads/$roadId'
    | '/roads'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/graph-analytics/$predictionId'
    | '/hotspots'
    | '/map'
    | '/police'
    | '/predictions'
    | '/reports'
    | '/submit'
    | '/admin/data-management'
    | '/admin/history'
    | '/admin/model-registry'
    | '/admin/moderation'
    | '/predictions/$predictionId'
    | '/roads/$roadId'
    | '/roads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  HotspotsRoute: typeof HotspotsRoute
  MapRoute: typeof MapRoute
  PoliceRoute: typeof PoliceRoute
  PredictionsRoute: typeof PredictionsRoute
  ReportsRoute: typeof ReportsRoute
  SubmitRoute: typeof SubmitRoute
  AnalyticsPredictionIdRoute: typeof AnalyticsPredictionIdRoute
  PredictionsPredictionIdRoute: typeof PredictionsPredictionIdRoute
  RoadsRoadIdRoute: typeof RoadsRoadIdRoute
  RoadsIndexRoute: typeof RoadsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotspots': {
      id: '/hotspots'
      path: '/hotspots'
      fullPath: '/hotspots'
      preLoaderRoute: typeof HotspotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph-analytics/$predictionId': {
      id: '/graph-analytics/$predictionId'
      path: '$predictionId'
      fullPath: '/graph-analytics/$predictionId'
      preLoaderRoute: typeof AnalyticsPredictionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/police': {
      id: '/police'
      path: '/police'
      fullPath: '/police'
      preLoaderRoute: typeof PoliceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions': {
      id: '/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof PredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roads/': {
      id: '/roads/'
      path: '/roads'
      fullPath: '/roads/'
      preLoaderRoute: typeof RoadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roads/$roadId': {
      id: '/roads/$roadId'
      path: '/roads/$roadId'
      fullPath: '/roads/$roadId'
      preLoaderRoute: typeof RoadsRoadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions/$predictionId': {
      id: '/predictions/$predictionId'
      path: '/predictions/$predictionId'
      fullPath: '/predictions/$predictionId'
      preLoaderRoute: typeof PredictionsPredictionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/model-registry': {
      id: '/admin/model-registry'
      path: '/model-registry'
      fullPath: '/admin/model-registry'
      preLoaderRoute: typeof AdminModelRegistryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/history': {
      id: '/admin/history'
      path: '/history'
      fullPath: '/admin/history'
      preLoaderRoute: typeof AdminHistoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/data-management': {
      id: '/admin/data-management'
      path: '/data-management'
      fullPath: '/admin/data-management'
      preLoaderRoute: typeof AdminDataManagementRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDataManagementRoute: typeof AdminDataManagementRoute
  AdminHistoryRoute: typeof AdminHistoryRoute
  AdminModelRegistryRoute: typeof AdminModelRegistryRoute
  AdminModerationRoute: typeof AdminModerationRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDataManagementRoute: AdminDataManagementRoute,
  AdminHistoryRoute: AdminHistoryRoute,
  AdminModelRegistryRoute: AdminModelRegistryRoute,
  AdminModerationRoute: AdminModerationRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  HotspotsRoute: HotspotsRoute,
  MapRoute: MapRoute,
  PoliceRoute: PoliceRoute,
  PredictionsRoute: PredictionsRoute,
  ReportsRoute: ReportsRoute,
  SubmitRoute: SubmitRoute,
  AnalyticsPredictionIdRoute: AnalyticsPredictionIdRoute,
  PredictionsPredictionIdRoute: PredictionsPredictionIdRoute,
  RoadsRoadIdRoute: RoadsRoadIdRoute,
  RoadsIndexRoute: RoadsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
